### ISSUE TITLE
Document measurement units & external vs internal

### ISSUE THREAD

**Issue by tfmorris** [datasets/ISO-Container-Codes#2]
Since this is presumably supposed to be machine usable, it would be good to know what units the measurements are in and whether they're internal or external measurements.

As a guess, it looks like they could be external measurements in feet.

**Comment by cmsdroff** [comment]
Thanks for the feedback, all shipping containers are measured in feet, I'll update the description fields to indicate this tomorrow

**Comment by tfmorris** [comment]
Oops, sorry. Missed that the description include units.

**Comment by cmsdroff** [comment]
No worries, appreciate the feedback
